# Generated by Django 4.2.7 on 2023-11-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="useremotiondata",
            table="user_emotion_data",
        ),
        migrations.AlterModelTable(
            name="userpreferences",
            table="user_preferences",
        ),
    ]
