# Generated by Django 4.2.7 on 2023-11-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("song_recommendation", "0005_remove_song_album"),
        ("user_management", "0002_alter_useremotiondata_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpreferences",
            name="preference_id",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="artist_id",
            field=models.ForeignKey(
                max_length=45,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="song_recommendation.artist",
            ),
        ),
    ]
