# Generated by Django 4.2.7 on 2023-11-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "album_id",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("album_name", models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "artist_id",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("artist_name", models.CharField(max_length=45)),
                ("artist_image_url", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "song_id",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=45)),
                (
                    "album",
                    models.ForeignKey(
                        db_column="album_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="song_recommendation.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongEmotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion", models.CharField(max_length=45)),
                (
                    "song_id",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="song_recommendation.song",
                    ),
                ),
            ],
            options={
                "unique_together": {("song_id", "emotion")},
            },
        ),
        migrations.CreateModel(
            name="SongArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist_id",
                    models.ForeignKey(
                        db_column="artist_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="song_recommendation.artist",
                    ),
                ),
                (
                    "song_id",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="song_recommendation.song",
                    ),
                ),
            ],
            options={
                "unique_together": {("song_id", "artist_id")},
            },
        ),
    ]
