# Generated by Django 4.2.7 on 2023-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("song_recommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="artist_popularity",
            field=models.IntegerField(default=0),
        ),
    ]
