# Generated by Django 4.2.7 on 2023-11-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("song_recommendation", "0002_artist_artist_popularity"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="album",
            table="album",
        ),
        migrations.AlterModelTable(
            name="artist",
            table="artist",
        ),
        migrations.AlterModelTable(
            name="song",
            table="song",
        ),
        migrations.AlterModelTable(
            name="songartist",
            table="song_artist",
        ),
        migrations.AlterModelTable(
            name="songemotion",
            table="song_emotion",
        ),
    ]
