# Generated by Django 4.2.7 on 2023-11-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("song_recommendation", "0003_alter_album_table_alter_artist_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
    ]
