# Generated by Django 4.2.7 on 2023-11-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("song_recommendation", "0004_song_popularity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
    ]
